# Generated by Django 3.0.3 on 2020-02-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_prdsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('CCNumber', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('NameOnCard', models.CharField(max_length=80)),
                ('CCEXDate', models.DateField()),
                ('VCode', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDColor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSize',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X Large'), ('XXL', 'XX Large'), ('XXXL', 'XXX Large')], default='M', max_length=4),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
