# Generated by Django 3.0.3 on 2020-02-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_prdimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='PRDImage',
            new_name='PRDiImage',
        ),
    ]
