# Generated by Django 3.0.3 on 2020-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='DeleveryCOST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], default='size', max_length=30),
        ),
    ]
