# Generated by Django 3.0.3 on 2020-05-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200503_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDSize',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X Large', 'X Large'), ('XX Large', 'XX Large'), ('XXX Large', 'XXX Large')], default='M', max_length=15),
        ),
    ]
