# Generated by Django 3.0.3 on 2020-05-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200516_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='DeleveryCOST',
        ),
    ]
