# Generated by Django 3.0.3 on 2020-05-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_deleverycost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
