# Generated by Django 3.0.3 on 2020-05-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200516_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage1',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDImage2',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
