# Generated by Django 3.0.3 on 2020-05-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200517_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage1',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDImage2',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATYName',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDColor',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSize',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X Large', 'X Large'), ('XX Large', 'XX Large'), ('XXX Large', 'XXX Large')], default='Medium', max_length=15),
        ),
    ]
