# Generated by Django 4.0 on 2021-12-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200517_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDUnitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
