# Generated by Django 3.0.3 on 2020-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='picusers/no.png', upload_to='picusers/admins/'),
        ),
    ]
