# Generated by Django 3.0.3 on 2020-05-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_auto_20200515_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emailAdress',
        ),
    ]
