# Generated by Django 3.0.3 on 2020-05-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0005_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
